CREATE TABLE USERS(
	id SERIAL NOT NULL UNIQUE,
	e_mail TEXT NOT NULL UNIQUE
);

CREATE TABLE ROOMS(
	id SERIAL NOT NULL UNIQUE,
	name TEXT NOT NULL,
	wall TEXT NOT NULL,
	floor TEXT NOT NULL,
	ceiling TEXT NOT NULL,
	furniture TEXT NOT NULL
);

CREATE TABLE MODELS(
	id SERIAL NOT NULL UNIQUE,
	modelUrl TEXT NOT NULL,
	name TEXT NOT NULL,
	price FLOAT NOT NULL,
	stock INTEGER
);

CREATE TABLE SHOPPING_LIST(
	id SERIAL NOT NULL UNIQUE,
	user_id INTEGER NOT NULL,
	model_id INTEGER NOT NULL,
	
	FOREIGN KEY (user_id) REFERENCES USERS(id),
	FOREIGN KEY (model_id) REFERENCES MODELS(id)
);

CREATE TABLE CART(
	id SERIAL NOT NULL UNIQUE,
	user_id INTEGER NOT NULL,
	shoppingList_id INTEGER NOT NULL,
	
	FOREIGN KEY (user_id) REFERENCES USERS(id),
	FOREIGN KEY (shoppingList_id) REFERENCES SHOPPING_LIST(id)
);


CREATE TABLE ROOM_USERS(
	id SERIAL NOT NULL UNIQUE,
	user_id INTEGER NOT NULL,
	scene_id INTEGER NOT NULL,
	
	FOREIGN KEY (user_id) REFERENCES USERS(id),
	FOREIGN KEY (scene_id) REFERENCES ROOMS(id)
);

CREATE TABLE ROOM_MODEL(
	id SERIAL NOT NULL UNIQUE,
	scene_id INTEGER NOT NULL,
	model_id INTEGER NOT NULL,
	x INTEGER NOT NULL,
	y INTEGER NOT NULL,
	z INTEGER NOT NULL,

	
	FOREIGN KEY (scene_id) REFERENCES ROOMS(id),
	FOREIGN KEY (model_id) REFERENCES MODELS(id)
);