CREATE TABLE USERS(
	id SERIAL NOT NULL UNIQUE,
	e_mail TEXT NOT NULL
);

CREATE TABLE ROOMS(
	id SERIAL NOT NULL UNIQUE,
	name TEXT NOT NULL
);

CREATE TABLE MODELS(
	id SERIAL NOT NULL UNIQUE,
	model BYTEA,
	name TEXT NOT NULL,
	price FLOAT NOT NULL,
	stock INTEGER
);

CREATE TABLE CART(
	id SERIAL NOT NULL UNIQUE,
	user_id INTEGER NOT NULL,
	
	FOREIGN KEY (user_id) REFERENCES USERS(id)
);

CREATE TABLE SHOPPING_LIST(
	id SERIAL NOT NULL UNIQUE,
	user_id INTEGER NOT NULL,
	model_id INTEGER NOT NULL,
	
	FOREIGN KEY (user_id) REFERENCES USERS(id),
	FOREIGN KEY (model_id) REFERENCES MODELS(id)
);

CREATE TABLE ROOM_USERS(
	id SERIAL NOT NULL UNIQUE,
	user_id INTEGER NOT NULL,
	scene_id INTEGER NOT NULL,
	
	FOREIGN KEY (user_id) REFERENCES USERS(id),
	FOREIGN KEY (scene_id) REFERENCES ROOMS(id)
);

CREATE TABLE ROOM_MODEL(
	id SERIAL NOT NULL UNIQUE,
	scene_id INTEGER NOT NULL,
	model_id INTEGER NOT NULL,
	
	FOREIGN KEY (scene_id) REFERENCES ROOMS(id),
	FOREIGN KEY (model_id) REFERENCES MODELS(id)
);